#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_memory_limit --value=512M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# INITIALIZE MULTIMEDIA DIRECTORIES
#================================================
ynh_script_progression "Initializing multimedia directories..."

ynh_multimedia_build_main_dir
ynh_multimedia_addfolder --source_dir="$data_dir" --dest_dir="$app"
ynh_multimedia_addaccess $app

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

app_key=$(ynh_string_random --length=32)
ynh_app_setting_set --key="app_key" --value="$app_key"
ynh_config_add --template="env" --destination="$install_dir/.env"

#=================================================
# INITIALIZE THE APP
#=================================================
ynh_script_progression "Initializing $app..."

pushd $install_dir
	ynh_exec_as_app php$php_version artisan koel:init --no-assets --no-interaction --quiet
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
