#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_memory_limit --value=512M

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#================================================
ynh_script_progression "Initializing multimedia directories..."

ynh_multimedia_build_main_dir
ynh_multimedia_addfolder --source_dir="$data_dir" --dest_dir="$app"
ynh_multimedia_addaccess $app

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

app_key=$(ynh_string_random --length=32)
ynh_app_setting_set --key="app_key" --value="$app_key"
ynh_config_add --template="env" --destination="$install_dir/.env"

#=================================================
# INITIALIZE THE APP
#=================================================
ynh_script_progression "Initializing $app..."

pushd $install_dir
	ynh_exec_as_app php$php_version artisan koel:init --no-assets --no-interaction --quiet
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
